name: spring-deploy
description: |
  An example Architect component to deploy and run a simple Spring Boot app.
keywords:
  - java
  - spring
services:
  app:
    build:
      context: .
    interfaces:
      main:
        port: 5000
        ingress:
          subdomain: app
    environment:
      SPRING_PORT: 5000
      ENVIRONMENT: prod
