apiVersion: v1
kind: Service
metadata:
  name: "service-spring-deploy"
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  type: LoadBalancer
  selector:
    app: spring-deploy
